# Generated by Django 4.2.5 on 2023-10-08 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('APPROVED', 'Approved'), ('DECLINED', 'Declined'), ('IN_PROCESS', 'InProcess')], max_length=20),
        ),
    ]
