# Generated by Django 4.2.5 on 2023-10-14 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_alter_ticket_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='reject_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Low', max_length=10),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('InProcess', 'InProcess'), ('InRestoration', 'InRestoration'), ('DeclinedToRestore', 'DeclinedToRestore'), ('ApproveRestore', 'ApproveRestore'), ('Rejected', 'Rejected'), ('Done', 'Done')], default='Active', max_length=20),
        ),
    ]
