# Generated by Django 4.2.5 on 2023-10-14 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_ticket_reject_reason_alter_ticket_priority_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('InProcess', 'InProcess'), ('InRestoration', 'InRestoration'), ('DeclineToRestore', 'DeclinedToRestore'), ('ApproveRestore', 'ApproveRestore'), ('Rejected', 'Rejected'), ('Done', 'Done')], default='Active', max_length=20),
        ),
    ]
