# Generated by Django 4.2.5 on 2023-10-15 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_ticket_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restorationticketrequest',
            name='created_date',
        ),
    ]
