# Generated by Django 4.2.5 on 2023-10-16 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_remove_restorationticketrequest_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('InProcess', 'InProcess'), ('InRestoration', 'InRestoration'), ('Decline', 'Decline'), ('Approve', 'Approve'), ('Done', 'Done')], default='Active', max_length=20),
        ),
    ]
