# Generated by Django 4.2.5 on 2023-10-16 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0011_alter_ticket_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('InProcess', 'InProcess'), ('InRestoration', 'InRestoration'), ('Declined', 'Declined'), ('Approved', 'Approved'), ('Done', 'Done')], default='Active', max_length=20),
        ),
    ]
