# Generated by Django 4.2.5 on 2023-10-17 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0012_alter_ticket_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='reject_reason',
        ),
    ]
