# Generated by Django 4.2.5 on 2023-10-20 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0015_alter_ticket_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='decline_reason',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
